"""add quantity to order_items

Revision ID: 901ce2f5af6a
Revises: fd1769b2141f
Create Date: 2026-06-18 20:44:44.196440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901ce2f5af6a'
down_revision: Union[str, Sequence[str], None] = 'fd1769b2141f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'quantity')
    # ### end Alembic commands ###
