"""init fresh schema

Revision ID: fde5022e6700
Revises: f1792d4474d9
Create Date: 2026-06-22 17:24:34.052867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde5022e6700'
down_revision: Union[str, Sequence[str], None] = 'f1792d4474d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'total_price')
    op.add_column('orders', sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_price')
    op.add_column('order_items', sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###
